### ISSUE TITLE
you lost the last bottle net layer (kernel 5, out 960)

### ISSUE THREAD

**Issue by mttbx** [frotms/MobilenetV3_Tensorflow#2]
you lost the last bottle net layer (kernel 5, out 960)

**Comment by frotms** [comment]
here is the last bottle net layer (kernel 5, out 960) @mttbx 
[https://github.com/frotms/MobilenetV3-Tensorflow/blob/master/mobilenet_v3.py#L272](https://github.com/frotms/MobilenetV3-Tensorflow/blob/master/mobilenet_v3.py#L272)

**Comment by mttbx** [comment]
there are two conv layer which is kernel 5x5 and out 960, you only have one.

**Comment by mttbx** [comment]
![1](https://user-images.githubusercontent.com/38148377/59140981-cb1a8e80-89d7-11e9-9498-8c2b2ce16497.png)

**Comment by frotms** [comment]
@mttbx I think there is just one convolution layer that out 960.

**Comment by mttbx** [comment]
yeah, my mistake
